Igalia/snabbswitch

src/apps/lwaftr/default_conf, src/apps/lwaftr/lwaftr.lua
A series of patches with some minor changes.
=> Minor changes

src/apps/lwaftr/icmp.lua
Copying the data using C.memmove removes garbage collection cycles (as reported by LuaJIT's profiler), improving performance. However, for small size packets, it seems C.memmove is slower than copying the data directly with a loop. So, I added an heuristic to determine whether to use C.memmove or a loop.
More precisely, the first test below decreased it's performance (to 3.5) if C.memmove was used (the tests uses a packet size of 28. I set the threshold to 32 but actually I don't have data to know what's the right value).
Before:                                                                         
```                                                                       
Benchmarking: from-internet IPv4 packet found in the binding table,             
needs IPv6 fragmentation, DF set, …
```
=> Rewrite loop using C.memmove

src/apps/lwaftr/benchui.lua, src/apps/lwaftr/lwaftr.lua
Before:
statisticsv6: 1.916 MPPS, 9.046 Gbps.
statisticsv4: 1.916 MPPS, 7.819 Gbps.
After:
statisticsv6: 2.277 MPPS, 10.747 Gbps.
statisticsv4: 2.277 MPPS, 9.290 Gbps.
=> Lwaftr noodling

README.lwaftr.md, docs/README.benchmarking.md, docs/README.bindingtable.md, docs/README.build.md, docs/README.configuration.md, docs/README.first.md, docs/README.performance.md, docs/README.rfccompliance.md, docs/README.testing.md, docs/README.troubleshooting.md, docs/build-all.sh
This includes how to build it, how to run it, how to configure it,
how it complies to several RFCs, how to run its tests, how to benchmark
it, and some troubleshooting and performance tips.
=> Added documentation on the lwaftr

src/apps/lwaftr/lwaftr.lua
* src/apps/lwaftr/lwaftr.lua: Add back-pressure to avoid burning cycles
on packets that we won't be able to handle anyway.
=> Add back-pressure to the lwaftr

src/program/snabb_lwaftr/run/README, src/program/snabb_lwaftr/run/run.lua
=> Better verbosity control in lwaftr run

docs/README.first.md, docs/README.virtualization.md, docs/build-all.sh
* docs/README.first.md: Add chapter.
* docs/README.virtio.md -> docs/README.virtualization.md: Rename.
* docs/build-all.sh: Convert chapter to pdf.
=> Add 'virtualization' chapter to README.first.md

src/apps/lwaftr/fragmentv6.lua, src/program/snabb_lwaftr/doc/README.troubleshooting.md, src/program/snabb_lwaftr/tests/end-to-end/benchrun.lua, src/program/snabb_lwaftr/tests/end-to-end/lwstats.py
=> Replace tabs for spaces

src/program/snabb_lwaftr/transient/README
=> Fix 'transient' README

src/apps/lwaftr/fragmentv4_test.lua, src/apps/lwaftr/icmp.lua
This bug was solved in 97352cf9.
=> Remove setting of IPv4 packet to version 4

src/apps/lwaftr/conf.lua
A patch I did while working on #90 but I didn't need it in the end. I think it's still nice to push it in master.
=> Write _conff function as multiline string

src/apps/lwaftr/lwaftr.lua
It was being cleaned too aggressively, corrupting it when there was an
attempt to assemble a packet before all the fragments had arrived.
=> Clean the packet cache only on invalid reassembly

src/apps/lwaftr/fragmentv4_test.lua
This adds an additional test case in fragmentv4_test.lua, which tests whether
fragmenting a packet which has 802.1Q VLAN tagging works properly. Also,
helper functions used for testing are modified to recognize the tag protocol
identifier (TPID) and treat tagged packets accordingly.
=> Add test case for IPv4 fragmentation with VLAN tagging

src/apps/lwaftr/fragmentv4.lua, src/apps/lwaftr/fragmentv6.lua
Also updated the fragmentv4 comment about the meaning of MTU.
Requested on https://github.com/Igalia/snabbswitch/pull/126
=> New internal variable for L2 MTU

src/program/snabb_lwaftr/tests/data/add-vlan.sh
Also, removed a file to not automatically regenerate from the list.
=> Added IPv4 fragment reassembly tests

src/apps/lwaftr/binary_search.dasl, src/apps/lwaftr/multi_copy.dasl, src/apps/lwaftr/podhashmap.lua, src/apps/lwaftr/test_phm_create.lua, src/apps/lwaftr/test_phm_lookup.lua, src/apps/lwaftr/test_phm_streaming_lookup.lua, src/dasm.lua, src/dasm_mm.lua, src/dasm_proto.h, src/dasm_x64.lua, src/dasm_x86.h, src/dasm_x86.lua, src/dynasm.lua, src/lib/pmu.lua
This is a cleaned up version of #97.
=> Add PodHashMap

src/apps/lwaftr/podhashmap.lua
In the PodHashMap insertion test, don't create the values via an
ffi.new() with a complex initializer.  Besides not being how we would do
this in practice, this was causing the test loop to be blacklisted,
invalidating later results.  The result would be tests that ran really
slowly.  I had seen this in the past and chalked up the bad bimodal
distribution to something random in the memory subsystem (that needed
investigating) but didn't realize it was actually something random in
LuaJIT.  I didn't always see it because there is something random about
the way that LuaJIT decides to start tracing.  (I really wish it were
deterministic!)
=> Fix bad bimodal distribution in PodHashMap performance self-test

src/apps/lwaftr/lwaftr.lua
If hairpinning is enabled, the source address and port of the original packet
must be checked to see if they are in the binding table. The wrong bytes were
being compared against binding table entries.
=> Fixed incoming ICMPv6+hairpinning support

src/program/snabb_lwaftr/check/check.lua
=> Reduce 'snabb-lwaftr check' running time

src/apps/lwaftr/address_map.lua, src/apps/lwaftr/rangemap.lua, src/program/snabb_lwaftr/compile_address_map/compile_address_map.lua
This PR implements the auto-compilation strategy discussed in #186.
=> Auto compile address map

src/apps/lwaftr/icmp.lua
=> Remove unused script-level local variable

src/program/lwaftr/bench/bench.lua, src/program/lwaftr/run/run.lua, src/program/lwaftr/transient/transient.lua
We have been seeing some latency jitter recently and we want to
eliminate possible causes.
=> Enable busy-waiting by default in the lwaftr

src/apps/lwaftr/lwaftr.lua
Thanks to Marcel Wiget for the report and initial fix.
=> Fix extraction of source port from tunneled ICMP packets.

src/program/lwaftr/run/README, src/program/lwaftr/run/run.lua
Also fix -vv and remove documentation for -u.
=> Add --ring-buffer-size option to --run

src/program/lwaftr/setup.lua
This reverts commit e3bb0608bd6899d77e71ebfd9ae499d3c9b247bf.
=> Revert "Fix vmdq setting"

src/apps/lwaftr/lwaftr.lua
If a packet's TTL is or will be 0 after processing, free it.  Fixes a
memory leak.  Thanks to Diego Pino for spotting this one.
Note that this also changes decrement_ttl to never increase the TTL,
which of course makes sense.  We should drop incoming packets with a TTL
of 0 or 1; the former because we shouldn't *receive* packets with TTL=0
but we can't control that, and we shouldn't *send* packets with TTL=0
because of RFC 1122.
=> Drop dead incoming packets

src/apps/lwaftr/generator.lua, src/program/lwaftr/README, src/program/lwaftr/generator/README, src/program/lwaftr/generator/generator.lua
* Improve docs.
* Remove non required or non supported flags.
* PSID in IPv6 was hardcoded.
* Add duration flag.
* Documented tool in lwaftr/README as well as `generate-binding-table`.
=> Several improvements to generator interface

src/program/lwaftr/doc/CHANGELOG.md, src/program/lwaftr/doc/README.benchmarking.md, src/program/lwaftr/doc/README.bindingtable.md, src/program/lwaftr/doc/README.md, src/program/lwaftr/doc/README.rfccompliance.md
Gol durnit, I had these changes locally but didn't commit them.  A follow-on to https://github.com/Igalia/snabbswitch/pull/278.  @kbara would you please take a look?  Tx.
=> Missing documentation fixes
